from src.libs.resume_and_cover_builder.template_base import (
    prompt_header_template,
    prompt_education_template,
    prompt_working_experience_template,   # 仍保留供其它模块引用，但这里不再用于生成
    prompt_projects_template,
    prompt_additional_skills_template,
    prompt_achievements_template,
)

# ---------- Prompts ----------

prompt_header = """
Act as an HR expert and resume writer specializing in ATS-friendly resumes. Your task is to create a professional and polished header for the resume. The header should:

1. **Contact Information**: Include your full name, city and country, phone number, email address, LinkedIn profile, and GitHub profile.
2. **Formatting**: Ensure the contact details are presented clearly and are easy to read.

To implement this:
- If any of the contact information fields (e.g., LinkedIn profile, GitHub profile) are not provided (i.e., `None`), omit them from the header.

- **My information:**  
  {personal_information}
""" + prompt_header_template

prompt_education = """
Act as an HR expert and resume writer with a specialization in creating ATS-friendly resumes. Your task is to articulate the educational background for a resume, ensuring it aligns with the provided job description. For each educational entry, ensure you include:

1. **Institution Name and Location**: Specify the university or educational institution’s name and location.
2. **Degree and Field of Study**: Clearly indicate the degree earned and the field of study.
3. **Grade**: Include your Grade if it is strong and relevant.
4. **Relevant Coursework**: List key courses with their grades to showcase your academic strengths. If no coursework is provided, omit this section from the template.

To implement this, follow these steps:
- If the exam details are not provided (i.e., `None`), skip the coursework section when filling out the template.
- If the exam details are available, fill out the coursework section accordingly.

- **My information:**  
  {education_details}

- **Job Description:**  
  {job_description}
""" + prompt_education_template

# ⚠️ 工作经历提示在本 strings 中弃用：由子类 LLMResumeJobDescription.generate_work_experience_section 内部的“edit-only”提示负责
prompt_working_experience = """
(Deprecated in this strings module: work experience is generated by an edit-only prompt inside LLMResumeJobDescription.generate_work_experience_section.)
"""

prompt_projects = """
Act as an HR expert and resume writer with a specialization in creating ATS-friendly resumes. Your task is to highlight notable side projects based on the provided job description. For each project, ensure you include:

1. **Project Name and Link**: Provide the name of the project and include a link to the GitHub repository or project page.
2. **Project Details**: Describe any notable recognition or achievements related to the project, such as GitHub stars or community feedback.
3. **Technical Contributions**: Highlight your specific contributions and the technologies used in the project.

Ensure that the project descriptions demonstrate your skills and achievements relevant to the job description.

To implement this:
- If any of the project details (e.g., link, achievements) are not provided (i.e., `None`), omit those sections when filling out the template.

- **My information:**  
  {projects}

- **Job Description:**  
  {job_description}
""" + prompt_projects_template

prompt_achievements = """
Act as an HR expert and resume writer with a specialization in creating ATS-friendly resumes. Your task is to list significant achievements based on the provided job description. For each achievement, ensure you include:

1. **Award or Recognition**: Clearly state the name of the award, recognition, scholarship, or honor.
2. **Description**: Provide a brief description of the achievement and its relevance to your career or academic journey.

Ensure that the achievements are clearly presented and effectively highlight your accomplishments.

To implement this:
- If any of the achievement details (e.g., certifications, descriptions) are not provided (i.e., `None`), omit those sections when filling out the template.

- **My information:**  
  {achievements}

- **Job Description:**  
  {job_description}
""" + prompt_achievements_template


prompt_additional_skills = """
Act as a senior HR/ATS resume editor. Craft an **Additional Skills** section that is tightly aligned with the target **Job Description & Requirements** while remaining faithful to the candidate’s background.

Goals
- **Coverage:** Aim to cover **≥80%** of the core themes and requirements present in the job description.
- **Relevance-first:** Prioritize skills that directly support the JD’s responsibilities (e.g., C/C++, embedded/Linux, testing & debugging, CI/CD, documentation, performance & reliability, collaboration).
- **Non-duplication:** Do **not** repeat tools/skills that are already strongly emphasized in the candidate’s **Work Experience**; list them only if they are critical gaps for JD coverage and keep them concise.
- **Grounded augmentation:** You may perform **reasonable, brand-agnostic grouping/expansion** to improve alignment (e.g., “version control branching & code review”, “unit/integration testing”, “monitoring & logging”), but **do not fabricate specific brands/tools** that are not present in the inputs.

Rules
- Primary inputs are `languages`, `interests`, and `skills`. Use the **job_description** to:
  1) **Group and title** skills into sensible categories (e.g., Programming, Embedded/Linux, Testing & Debugging, CI/CD & DevOps, Documentation, Soft Skills, Languages).
  2) **Select** and **prioritize** items most relevant to the JD.
- Keep brand names **only** if they appear in the inputs; otherwise use generic capability terms.
- If a proficiency/level exists in the inputs, include it; otherwise omit levels (do not invent).
- Omit any empty sections. Eliminate placeholders or filler items.

Output Requirements
For each category produce one bullet/line with:
1) **Skill Category** — concise, JD-relevant label.
2) **Specific Skills** — comma-separated list, **deduplicated** vs. Work Experience-emphasized items; prefer capability phrasing when brands are absent.
3) **(Optional) Proficiency/Experience** — include only when present in inputs (e.g., “English (C1)”, “GoogleTest — unit tests & mocks”).

Formatting Hints
- Keep 4–6 categories maximum, ordered by JD relevance (top = must-have).
- Render languages as “Name (Level)” when level exists.
- Be concise and ATS-friendly (no long sentences).

My data (use these as the factual source; use job_description for grouping/prioritization only):
- languages: {languages}
- interests: {interests}
- skills: {skills}

Job Description (use to group/prioritize; do not invent brands not present above):
{job_description}
""" + prompt_additional_skills_template


summarize_prompt_template = """
As a seasoned HR expert, your task is to identify and outline the key skills and requirements necessary for the position of this job. Use the provided job description as input to extract all relevant information. This will involve conducting a thorough analysis of the job's responsibilities and the industry standards. You should consider both the technical and soft skills needed to excel in this role. Additionally, specify any educational qualifications, certifications, or experiences that are essential. Your analysis should also reflect on the evolving nature of this role, considering future trends and how they might affect the required competencies.

Rules:
Remove boilerplate text
Include only relevant information to match the job description against the resume

# Analysis Requirements
Your analysis should include the following sections:
Technical Skills: List all the specific technical skills required for the role based on the responsibilities described in the job description.
Soft Skills: Identify the necessary soft skills, such as communication abilities, problem-solving, time management, etc.
Educational Qualifications and Certifications: Specify the essential educational qualifications and certifications for the role.
Professional Experience: Describe the relevant work experiences that are required or preferred.
Role Evolution: Analyze how the role might evolve in the future, considering industry trends and how these might influence the required skills.

# Final Result:
Your analysis should be structured in a clear and organized document with distinct sections for each of the points listed above. Each section should contain:
This comprehensive overview will serve as a guideline for the recruitment process, ensuring the identification of the most qualified candidates.

# Job Description:

{text}


---

# Job Description Summary"""

